-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               8.0.37 - MySQL Community Server - GPL
-- Server OS:                    Win64
-- HeidiSQL Version:             12.7.0.6850
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for supplements
CREATE DATABASE IF NOT EXISTS `supplements` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `supplements`;

-- Dumping structure for table supplements.active_form
CREATE TABLE IF NOT EXISTS `active_form` (
  `form_id` int NOT NULL AUTO_INCREMENT,
  `form_description` text,
  `form_name` varchar(255) DEFAULT NULL,
  `nutrient_id` int NOT NULL,
  PRIMARY KEY (`form_id`)
) ENGINE=InnoDB AUTO_INCREMENT=102 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.active_form: ~9 rows (approximately)
INSERT INTO `active_form` (`form_id`, `form_description`, `form_name`, `nutrient_id`) VALUES
	(46, 'Retinol, a potent form of vitamin A, is hailed as a skincare superstar. This powerful retinoid works by increasing cell turnover, stimulating collagen production, and reducing the appearance of fine lines, wrinkles, and hyperpigmentation. Regularly incorporating retinol into your routine can visibly improve skin texture, minimize pores, and reveal a more youthful, radiant complexion.', 'Retinol', 1),
	(47, '<p>Retinal, also known as retinaldehyde, is a highly potent form of vitamin A that packs a punch when it comes to skin rejuvenation. Unlike its over-the-counter cousin, retinol, retinal works more efficiently at the cellular level, accelerating cell turnover and collagen production without the irritation often associated with retinoids.</p>  <p>Retinal targets a wide range of skin concerns, from fine lines and wrinkles to hyperpigmentation and acne. Its unique molecular structure allows it to penetrate deeper into the skin, delivering a more concentrated dose of vitamin A for maximum results. Dermatologists often recommend retinal as a stepping stone for those looking to transition from gentler retinoids to prescription-strength treatments. With consistent use, retinal can visibly improve skin\'s radiance, smoothness, and overall youthful appearance. As with any potent active, start slow and introduce retinal gradually to minimize potential dryness or sensitivity.</p>', 'Retinal', 1),
	(48, '<p>Thiamin diphosphate, also known as thiamine pyrophosphate, is the active form of Vitamin B1 (thiamine) and plays a crucial role in numerous metabolic processes within the human body. As a cofactor for several essential enzymes, thiamin diphosphate is essential for the proper conversion of carbohydrates, fats, and proteins into energy.</p>   <p>Beyond its role in energy production, thiamin diphosphate also contributes to the maintenance of a healthy nervous system and supports the proper function of the cardiovascular system. It may also help to support cognitive function and overall brain health, making it an important nutrient for maintaining optimal well-being.</p>', 'Thiamin diphosphate (thiamine pyrophosphate)', 2),
	(49, '<p>Thiamin hydrochloride is a synthetic form of Vitamin B1 (thiamine) that is commonly used in dietary supplements and fortified foods. While it shares many of the same functions and benefits as the naturally occurring form of thiamine, thiamin hydrochloride is a more stable and readily available version of the nutrient.</p>   <p>Like its natural counterpart, thiamin hydrochloride plays a crucial role in energy metabolism, supporting the conversion of carbohydrates, fats, and proteins into usable energy. It also contributes to the maintenance of a healthy nervous system and may help support cognitive function and overall brain health.</p>', 'Thiamin hydrochloride', 2),
	(50, '<p>Flavin adenine dinucleotide, commonly known as FAD, is a coenzyme derived from the B-complex vitamin, riboflavin (Vitamin B2). FAD plays a crucial role in numerous metabolic processes, serving as a cofactor for a wide range of enzymes involved in energy production, antioxidant defense, and various other biochemical reactions.</p>   <p>As an essential component of the mitochondrial electron transport chain, FAD is instrumental in the efficient conversion of nutrients into usable energy in the form of ATP. It also contributes to the regulation of cellular redox balance by participating in the recycling of antioxidant molecules, such as glutathione, to help protect cells from oxidative stress.</p>', 'Flavin adenine dinucleotide (FAD)', 3),
	(51, '<p>Flavin mononucleotide, or FMN, is a cofactor derived from the B-complex vitamin, riboflavin (Vitamin B2). FMN plays a crucial role in numerous metabolic processes, serving as an essential component in various enzymatic reactions that are responsible for energy production, cellular respiration, and antioxidant defense.</p>   <p>As a key participant in the mitochondrial electron transport chain, FMN helps to facilitate the efficient conversion of nutrients into usable energy in the form of ATP. It also contributes to the regulation of cellular redox balance by supporting the activity of antioxidant enzymes that help protect cells from oxidative stress.</p>', 'Flavin mononucleotide (FMN)', 3),
	(52, '<p>Niacinamide, also known as nicotinamide, is a form of Vitamin B3 that plays a crucial role in various physiological processes. Unlike its counterpart, niacin, niacinamide is generally well-tolerated and does not cause the characteristic flushing reaction associated with high doses of niacin.</p>   <p>As a precursor to the important coenzymes NAD and NADP, niacinamide is essential for energy production, DNA repair, and the regulation of cellular metabolism. It has also been studied for its potential benefits in skin health, reducing the appearance of fine lines and wrinkles, and improving the overall complexion.</p>', 'Niacinamide (nicotinamide)', 4),
	(53, '<p>Niacin, also known as nicotinic acid, is a form of Vitamin B3 that plays a crucial role in various physiological processes. Unlike its counterpart, niacinamide, niacin can cause a characteristic flushing reaction, which is often used as an indicator of adequate intake.</p>   <p>As a precursor to the important coenzymes NAD and NADP, niacin is essential for energy production, DNA repair, and the regulation of cellular metabolism. It has also been studied for its potential benefits in improving cholesterol levels and supporting cardiovascular health.</p>', 'Niacin (Nicotinic Acid)', 4),
	(54, '<p>Cholecalciferol, or vitamin D3, is the most potent and bioavailable form of the "sunshine vitamin." Unlike other vitamins, vitamin D3 is uniquely produced in the skin when exposed to ultraviolet B (UVB) radiation from sunlight, making this the primary natural source for the majority of the population.</p>  <p>Vitamin D3 is essential for maintaining optimal calcium and phosphorus absorption, crucial for strong, healthy bones. It also plays a vital role in immune function, cardiovascular health, and even cancer prevention. Studies show vitamin D3 is more effectively utilized by the body compared to its plant-derived counterpart, vitamin D2.</p>  <p>To ensure adequate vitamin D3 levels, experts recommend regular, moderate sun exposure, allowing the skin to naturally synthesize this nutrient. For those unable to get sufficient sunlight, supplementation with vitamin D3 is a more effective option than vitamin D2. Monitoring vitamin D levels through blood tests can help determine the appropriate supplementation dose for individual needs.</p>', 'Cholecalciferol (Vitamin D3)', 11),
	(55, '<p>Ergocalciferol, or vitamin D2, is a form of vitamin D derived from plant sources, such as fungi and yeast. Unlike its counterpart, vitamin D3 (cholecalciferol), which is produced naturally in the skin through sun exposure, vitamin D2 is considered less potent and not as efficiently utilized by the body.</p>  <p>While vitamin D2 can be used to supplement vitamin D intake, it is less bioavailable and has a shorter half-life in the body compared to vitamin D3. This means that vitamin D3 is more effective at raising and maintaining optimal vitamin D levels in the blood.</p>  <p>For individuals unable to obtain sufficient vitamin D from sun exposure or dietary sources, supplementation with vitamin D3 is generally recommended over vitamin D2. However, vitamin D2 can still play a role in supporting overall health and may be a suitable option for those with specific dietary restrictions or preferences. Consulting with a healthcare professional is advised to determine the appropriate vitamin D supplementation strategy.</p>', 'Ergocalciferol (Vitamin D2)', 11),
	(56, '<p>Alpha-tocotrienol is a unique form of vitamin E that has gained attention for its potent antioxidant properties.</p>  <p>Emerging research suggests that alpha-tocotrienol may offer superior neuroprotective benefits compared to other vitamin E forms. It has been shown to assist in maintaining healthy brain function and supporting the integrity of the nervous system.</p>  <p>Additionally, alpha-tocotrienol exhibits anti-inflammatory effects and may help regulate cholesterol levels, contributing to overall cardiovascular well-being.</p>', 'Alpha-tocotrienol', 12),
	(57, '<p>Beta-tocotrienol, a unique member of the vitamin E family, has garnered attention for its diverse health benefits. Unlike the more common alpha-tocopherol, beta-tocotrienol possesses a distinct molecular structure that allows it to penetrate deep into cells, where it can effectively neutralize harmful free radicals and support overall cellular health.</p>  <p>Emerging research suggests that beta-tocotrienol may offer superior anti-cancer properties compared to other vitamin E forms. It has been shown to inhibit the growth and proliferation of various types of cancer cells, potentially due to its ability to modulate specific cellular signaling pathways.</p>', 'Beta-tocotrienol', 12),
	(58, '<p>Pantothenic acid, also known as Vitamin B5, is a water-soluble nutrient that plays a crucial role in various metabolic processes within the body. While it may not receive as much attention as some of its B-complex counterparts, pantothenic acid is essential for maintaining overall health and well-being.</p>   <p>As a key component of coenzyme A, pantothenic acid is involved in the metabolism of fats, carbohydrates, and proteins, helping to convert these macronutrients into usable energy. It also supports the function of the adrenal glands, which are responsible for producing hormones that help the body adapt to stress.</p>', 'Pantothenic acid', 5),
	(59, '<p>Coenzyme A, often abbreviated as CoA, is a crucial cofactor involved in numerous metabolic processes within the human body. As a derivative of the B-complex vitamin pantothenic acid, CoA plays a vital role in the breakdown and utilization of fats, carbohydrates, and amino acids for energy production.</p>   <p>In addition to its involvement in energy metabolism, CoA also participates in the synthesis of important biomolecules, such as lipids, cholesterol, and neurotransmitters. It is also essential for the proper functioning of the citric acid cycle, a key pathway in cellular respiration that generates ATP, the primary energy currency of the cell.</p>', 'Coenzyme A (CoA)', 5),
	(60, '<p>Pyridoxal 5\' Phosphate (PLP) is the active cofactor form of Vitamin B6, a water-soluble nutrient essential for a wide range of metabolic processes. As the primary coenzyme for numerous enzymes, PLP plays a crucial role in the metabolism of proteins, fats, and carbohydrates, as well as in the synthesis of neurotransmitters and hemoglobin.</p>   <p>PLP is involved in over 100 enzymatic reactions, making it a versatile and indispensable cofactor in the human body. It is particularly important for the proper functioning of the immune system, the nervous system, and the cardiovascular system, contributing to overall health and well-being.</p>', 'Pyridoxal 5\' phosphate (PLP)', 6),
	(61, '<p>Pyridoxamine 5\' Phosphate (PMP) is a lesser-known but equally important coenzyme form of Vitamin B6. While the more widely recognized pyridoxal 5\' phosphate (PLP) is the primary active form, PMP also plays a crucial role in various metabolic processes within the human body.</p>   <p>PMP is involved in the metabolism of amino acids, the conversion of carbohydrates to energy, and the synthesis of neurotransmitters. It also has antioxidant properties and has been studied for its potential to mitigate oxidative stress and inflammation, which are associated with various health conditions.</p>', 'Pyridoxamine 5\' phosphate (PMP)', 6),
	(62, 'p>Biotin, also known as Vitamin B7 or Vitamin H, is a vital nutrient that plays a crucial role in various metabolic processes within the human body. As a cofactor for several essential enzymes, biotin is involved in the metabolism of carbohydrates, fats, and proteins, as well as in the regulation of gene expression and cellular signaling.</p>   <p>Biotin\'s primary functions include supporting the health of skin, hair, and nails, aiding in the conversion of food into energy, and contributing to the proper functioning of the nervous system. It is also essential for the maintenance of healthy blood sugar levels and the synthesis of fatty acids.</p>', 'Biotin', 7),
	(63, '<p>Folic acid, also known as vitamin B9, is a crucial nutrient that plays a vital role in various physiological processes, particularly during pregnancy. As the synthetic form of folate, folic acid is essential for the proper development of the fetal neural tube, as well as the production of red blood cells and the maintenance of a healthy immune system.</p>   <p>In addition to its importance during pregnancy, folic acid is also crucial for the metabolism of amino acids, the synthesis of DNA and RNA, and the support of overall cardiovascular health. Adequate folic acid intake has been linked to a reduced risk of certain birth defects, as well as a lower incidence of heart disease, stroke, and certain types of cancer.</p>', 'Folic acid', 8),
	(64, '<p>Tetrahydrofolate (THF), also known as tetrahydrofolate, is the bioactive form of folate, a B-complex vitamin essential for various metabolic processes in the human body. As a critical cofactor, THF is involved in the synthesis of DNA and RNA, the metabolism of amino acids, and the regulation of cellular function.</p>   <p>THF plays a crucial role in the transfer of one-carbon units, which are essential for the production of new cells, the maintenance of genetic material, and the proper functioning of the nervous system. Adequate levels of THF have been linked to a reduced risk of neural tube defects, cardiovascular disease, and certain types of cancer.</p>', 'Tetrahydrofolate', 8),
	(65, '<p>Methylcobalamin, also known as methyl B12, is the biologically active form of vitamin B12, an essential nutrient required for numerous metabolic processes in the human body. As a cofactor for various enzymes, methylcobalamin plays a crucial role in the production of red blood cells, the synthesis of DNA and RNA, and the maintenance of a healthy nervous system.</p>   <p>Unlike other forms of vitamin B12, methylcobalamin is more readily absorbed and utilized by the body, making it a superior choice for individuals with certain genetic variations or medical conditions that affect B12 metabolism. Adequate levels of methylcobalamin have been linked to improved energy levels, cognitive function, and overall well-being.</p>', 'Methylcobalamin', 9),
	(66, '<p>Adenosylcobalamin, also known as coenzyme B12, is one of the two active forms of vitamin B12 in the human body. Unlike its counterpart, methylcobalamin, adenosylcobalamin is primarily involved in the conversion of nutrients into energy within the mitochondria, the powerhouses of our cells.</p>   <p>As a cofactor for various enzymes, adenosylcobalamin plays a crucial role in the metabolism of fats and proteins, the production of red blood cells, and the maintenance of a healthy nervous system. It is particularly important for individuals with certain genetic or medical conditions that affect B12 metabolism, as it can be more readily utilized by the body.</p>', 'Adenosylcobalamin', 9),
	(67, '<p>Cyanocobalamin is a synthetic form of vitamin B12, an essential nutrient required for numerous metabolic processes in the human body. While it is not the most bioavailable or active form of B12, cyanocobalamin is often used in dietary supplements and fortified foods due to its stability and relatively low cost.</p>   <p>Once absorbed, the body must convert cyanocobalamin into the active forms of vitamin B12, known as methylcobalamin and adenosylcobalamin. This conversion process can be less efficient for some individuals, particularly those with certain genetic variations or medical conditions that affect B12 metabolism.</p>', 'Cyanocobalamin', 9),
	(68, '<p>Ascorbic acid, more commonly known as vitamin C, is an essential nutrient with a wide range of beneficial effects on the human body. As a powerful antioxidant, ascorbic acid helps neutralize harmful free radicals, reducing the risk of cellular damage and supporting overall health.</p>   <p>In addition to its antioxidant properties, ascorbic acid plays a crucial role in the production of collagen, the structural protein that provides strength and elasticity to our skin, bones, and blood vessels. It also supports the immune system, enhancing the body\'s ability to fight off infections and illnesses.</p>', 'Ascorbic acid', 10),
	(69, '<p>Sodium ascorbate is a salt form of ascorbic acid, also known as vitamin C. Unlike the acidic nature of pure ascorbic acid, sodium ascorbate is a more stable and bioavailable form of the nutrient, making it easier for the body to absorb and utilize.</p>   <p>As an antioxidant, sodium ascorbate helps neutralize harmful free radicals, protecting cells from oxidative stress and supporting overall health. Additionally, it plays a crucial role in the production of collagen, the structural protein that provides strength and elasticity to our skin, bones, and blood vessels.</p>', 'Sodium ascorbate', 10),
	(70, '<p>Magnesium glycinate is a form of magnesium that is bonded to the amino acid glycine. This combination makes magnesium glycinate highly bioavailable, meaning it is readily absorbed and utilized by the body, while also being gentle on the digestive system.</p>   <p>Magnesium is an essential mineral that plays a crucial role in a variety of physiological processes, including energy production, muscle function, and nerve transmission. Magnesium glycinate is particularly beneficial for individuals who may experience digestive discomfort or loose stools when taking other forms of magnesium supplements.</p>', 'Magnesium Glycinate', 28),
	(71, ' <p>Magnesium citrate is a form of magnesium that is bonded to citric acid, creating a highly bioavailable and well-absorbed supplement. Unlike some other forms of magnesium, magnesium citrate is gentle on the digestive system, making it a popular choice for those seeking a supplemental source of this essential mineral.</p>   <p>Magnesium plays a vital role in numerous bodily functions, including energy production, muscle and nerve function, and bone health. Supplementing with magnesium citrate can help support overall health and well-being, particularly for individuals who may not be getting enough of this important nutrient from their diet.</p>', 'Magnesium Citrate', 28),
	(72, '<p>Calcium carbonate is a common and widely available form of calcium supplement. It is a naturally-occurring mineral that is derived from limestone and is often used in dietary supplements due to its cost-effectiveness and ability to provide the body with the essential mineral calcium.</p>   <p>Calcium is crucial for maintaining strong bones and teeth, as well as supporting various other bodily functions. Calcium carbonate is a popular choice for individuals looking to increase their calcium intake, as it is readily available and generally well-tolerated by most people.</p>', 'Calcium carbonate', 27),
	(73, '<p>Calcium citrate is a form of calcium supplement that is bound to the citric acid molecule, making it highly bioavailable and easily absorbed by the body. This form of calcium is often preferred over other types, such as calcium carbonate, due to its superior absorption and tolerability.</p>   <p>Calcium is an essential mineral that plays a crucial role in maintaining healthy bones and teeth, as well as supporting various other bodily functions. Calcium citrate is particularly beneficial for individuals who have difficulty absorbing calcium from dietary sources or who may experience gastrointestinal discomfort with other calcium supplements.</p>', 'Calcium citrate', 27),
	(74, '<p>Dipotassium phosphate is a mineral salt that is composed of potassium and phosphate. It is a versatile compound that has a wide range of applications, including use as a food additive, a buffer in pharmaceutical formulations, and a supplement in various industries.</p>   <p>As a source of both potassium and phosphate, dipotassium phosphate can be beneficial for individuals looking to support their overall mineral balance. Potassium is an essential electrolyte that plays a crucial role in maintaining healthy blood pressure, while phosphate is important for bone health and energy production.</p>', 'Dipotassium phosphate', 13),
	(75, '<p>Disodium phosphate is a mineral salt that is composed of sodium and phosphate. It is a widely used food additive and buffer in various industries, providing a range of functions such as pH adjustment, emulsification, and water-binding properties.</p>   <p>As a source of sodium and phosphate, disodium phosphate can be found in a variety of processed foods, including baked goods, dairy products, and canned foods. It is often used to enhance the texture, stability, and shelf-life of these products.</p>', 'Disodium phosphate', 13),
	(76, '<p>Potassium chloride is a mineral salt that is composed of the elements potassium and chlorine. It is an essential nutrient that plays a vital role in maintaining proper fluid balance, nerve function, and muscle contraction within the human body.</p>   <p>Beyond its use as a dietary supplement, potassium chloride has a wide range of applications in various industries. It is commonly used as a salt substitute, a food preservative, and an electrolyte replacement in medical settings. Additionally, it is an important component in the production of fertilizers, glass, and other industrial products.</p>', 'Potassium chloride', 14),
	(77, '<p>Potassium citrate is a mineral salt that is composed of the elements potassium and citrate. It is a multi-functional compound that is used in various industries, including the pharmaceutical, food, and personal care sectors.</p>   <p>In the medical field, potassium citrate is often used to treat conditions such as kidney stones, metabolic acidosis, and certain types of high blood pressure. It can help to regulate the body\'s pH levels and provide a source of the essential mineral potassium.</p>', 'Potassium citrate', 14),
	(78, '<p>Dimethyl sulfoxide (DMSO) is a highly studied and versatile compound that has a wide range of applications in various industries. It is a polar aprotic solvent known for its ability to penetrate the skin and facilitate the delivery of other substances.</p>   <p>DMSO has been explored for its potential therapeutic uses, particularly in the field of pain management and the treatment of inflammatory conditions. It is believed to possess anti-inflammatory, analgesic, and possibly even antioxidant properties, making it a subject of ongoing research.</p>', 'Dimethyl sulfoxide (DMSO)', 15),
	(79, '<p>Methylsulfonylmethane (MSM) is a naturally-occurring organic sulfur compound that has gained attention in the health and wellness community. It is found in various plants, animals, and even the human body, and is often used as a dietary supplement.</p>   <p>MSM is believed to possess anti-inflammatory and analgesic properties, making it a popular choice for individuals seeking relief from joint pain, muscle soreness, and other inflammatory conditions. Additionally, it may play a role in supporting the health of connective tissues, such as cartilage and tendons.</p>', 'Methylsulfonylmethane (MSM)', 15),
	(80, '<p>Sodium chloride, commonly known as salt, is a mineral compound composed of the elements sodium and chlorine. It is an essential nutrient that plays a vital role in maintaining fluid balance, nerve function, and muscle contraction within the human body.</p>   <p>Beyond its use in food preparation and as a dietary supplement, sodium chloride has a wide range of applications in various industries. It is commonly used in the production of glass, detergents, and other chemical products. Additionally, it is an important component in the treatment of water, the de-icing of roads, and the preservation of certain foods.</p>', 'Sodium chloride', 16),
	(81, ' <p>Sodium bicarbonate, also known as baking soda, is a versatile compound that has a wide range of applications in both household and medical settings. It is a salt composed of sodium and bicarbonate ions, and is known for its ability to neutralize acids and absorb odors.</p>   <p>In the household, sodium bicarbonate can be used as a cleaning agent, a deodorizer, and even a fire extinguisher. It is commonly found in baked goods, where it acts as a leavening agent, helping to create light and fluffy textures.</p>', 'Sodium bicarbonate', 16),
	(82, '<p>Sodium chloride, commonly known as table salt, is a mineral compound composed of the elements sodium and chlorine. It is an essential nutrient that plays a crucial role in maintaining fluid balance, nerve function, and muscle contraction within the human body.</p>   <p>Beyond its culinary uses, sodium chloride has a wide range of applications in various industries. It is used in the production of glass, detergents, and other chemical products. Additionally, it is an important component in the treatment of water, the de-icing of roads, and the preservation of certain foods.</p>', 'Sodium chloride', 17),
	(83, '<p>Calcium chloride is a chemical compound composed of calcium and chlorine. It is a salt that has a wide range of applications in various industries, including construction, agriculture, and water treatment.</p>   <p>In construction, calcium chloride is used as a de-icing agent, as it helps to lower the freezing point of water, making it effective for clearing snow and ice from roads and sidewalks. It is also added to concrete to accelerate the curing process, allowing for faster construction times.</p>', 'Calcium chloride', 17),
	(84, '<p>Ferrous sulfate, also known as iron sulfate, is a chemical compound composed of iron and sulfur. It is a widely used mineral supplement that plays a crucial role in the treatment of iron deficiency anemia, a common health condition characterized by a lack of healthy red blood cells.</p>   <p>When taken as a supplement, ferrous sulfate helps to replenish the body\'s iron levels, which are essential for the production of hemoglobin, the protein in red blood cells responsible for carrying oxygen throughout the body. This makes it an important therapeutic agent for individuals suffering from iron deficiency, including pregnant women, growing children, and those with certain medical conditions.</p>', 'Ferrous sulfate', 18),
	(85, '<p>Ferrous gluconate is a chemical compound that serves as a dietary supplement for individuals who are deficient in iron. It is a form of iron that is more easily absorbed by the body compared to other iron supplements, making it an effective solution for addressing iron-related health issues.</p>   <p>Unlike ferrous sulfate, ferrous gluconate is less likely to cause gastrointestinal side effects, such as constipation or nausea, making it a more tolerable option for many individuals. This makes it a popular choice for treating iron deficiency anemia, a condition that can lead to fatigue, weakness, and other health problems if left untreated.</p>', 'Ferrous gluconate', 18),
	(86, '<p>Selenomethionine is an organic form of the essential trace mineral selenium. It is a naturally occurring amino acid that plays a crucial role in various physiological processes within the human body, including antioxidant protection, thyroid function, and immune system support.</p>   <p>Unlike inorganic forms of selenium, selenomethionine is more readily absorbed and utilized by the body, making it a highly bioavailable source of this important nutrient. It can be found in a variety of food sources, such as Brazil nuts, seafood, and some plant-based foods, but many individuals may still require supplementation to meet their daily selenium needs.</p>', 'Selenomethionine', 19),
	(87, '<p>Sodium selenite is an inorganic form of the essential trace mineral selenium. It is a commonly used supplement that plays a crucial role in various physiological processes, including antioxidant protection, thyroid function, and immune system support.</p>   <p>Unlike the organic form of selenium, known as selenomethionine, sodium selenite is more readily absorbed and utilized by the body, making it an efficient way to maintain optimal selenium levels. It can be found in a variety of food sources, such as seafood, organ meats, and some plant-based foods, but many individuals may still require supplementation to meet their daily selenium needs.</p>', 'Sodium selenite', 19),
	(88, '<p>Zinc picolinate is a specialized form of the essential mineral zinc, known for its enhanced bioavailability and absorption compared to other zinc supplements. This unique compound combines zinc with picolinic acid, a naturally occurring compound that helps to facilitate the absorption of zinc in the body.</p>   <p>Zinc plays a vital role in a wide range of physiological processes, including immune function, wound healing, and the metabolism of proteins, carbohydrates, and fats. By using the zinc picolinate form, individuals can potentially experience improved zinc status and better support for these crucial bodily functions.</p>', 'Zinc picolinate', 20),
	(89, '<p>Zinc citrate is a form of the essential mineral zinc that is characterized by its enhanced bioavailability and absorption within the human body. Unlike some other zinc compounds, the citrate form helps to improve the utilization of this vital nutrient, making it an effective supplement for addressing zinc deficiencies.</p>   <p>Zinc plays a crucial role in a wide range of physiological processes, including immune function, wound healing, and the metabolism of proteins, carbohydrates, and fats. By using the zinc citrate form, individuals can potentially experience improved zinc status and better support for these crucial bodily functions.</p>', 'Zinc citrate', 20),
	(90, '<p>Manganese gluconate is a form of the essential trace mineral manganese that is often used in dietary supplements. This compound is characterized by its high bioavailability, making it an effective way for individuals to maintain adequate manganese levels within the body.</p>   <p>Manganese plays a crucial role in various physiological processes, including antioxidant defense, bone health, and carbohydrate and fat metabolism. By supplementing with manganese gluconate, individuals can help support these important functions and potentially address any deficiencies in this essential nutrient.</p>', 'Manganese gluconate', 21),
	(91, '  <p>Manganese picolinate is a specialized form of the essential trace mineral manganese that is known for its superior bioavailability and absorption within the human body. This unique compound combines manganese with picolinic acid, a naturally occurring substance that helps to facilitate the utilization of this vital nutrient.</p>   <p>Manganese plays a crucial role in various physiological processes, including antioxidant defense, bone health, and carbohydrate and fat metabolism. By using the manganese picolinate form, individuals can potentially experience enhanced manganese status and better support for these important bodily functions.</p>', 'Manganese picolinate', 21),
	(92, ' <p>Chromium picolinate is a specialized form of the essential trace mineral chromium that is known for its enhanced bioavailability and absorption within the human body. This unique compound combines chromium with picolinic acid, a naturally occurring substance that helps to facilitate the utilization of this vital nutrient.</p>   <p>Chromium plays a crucial role in the regulation of blood sugar levels and the metabolism of carbohydrates, fats, and proteins. By using the chromium picolinate form, individuals can potentially experience improved chromium status and better support for these important physiological processes.</p>', 'Chromium picolinate', 22),
	(93, '<p>Chromium chloride is a form of the essential trace mineral chromium that is often used in dietary supplements. This compound is characterized by its relatively high bioavailability, making it an effective way for individuals to maintain adequate chromium levels within the body.</p>   <p>Chromium plays a crucial role in the regulation of blood sugar levels and the metabolism of carbohydrates, fats, and proteins. By supplementing with chromium chloride, individuals can potentially experience improved chromium status and better support for these important physiological processes.</p>', 'Chromium chloride', 22),
	(94, '<p>Cupric oxide is a form of the essential mineral copper that is often used in dietary supplements. This compound is characterized by its relatively high bioavailability, making it an effective way for individuals to maintain adequate copper levels within the body.</p>   <p>Copper is a crucial trace mineral that plays a vital role in various physiological processes, including energy production, immune function, and the formation of red blood cells. By supplementing with cupric oxide, individuals can potentially support these important bodily functions and address any deficiencies in this essential nutrient.</p>', 'Cupric oxide', 23),
	(95, '<p>Cupric sulfate is a form of the essential mineral copper that is commonly used in dietary supplements. This compound is characterized by its high solubility and bioavailability, making it an effective way for individuals to maintain adequate copper levels within the body.</p>   <p>Copper is a crucial trace mineral that plays a vital role in various physiological processes, including energy production, immune function, and the formation of red blood cells. By supplementing with cupric sulfate, individuals can potentially support these important bodily functions and address any deficiencies in this essential nutrient.</p>', 'Cupric sulfate', 23),
	(96, '<p>Sodium iodide is a form of the essential mineral iodine that is commonly used in dietary supplements. This compound is characterized by its high bioavailability, making it an effective way for individuals to maintain adequate iodine levels within the body.</p>   <p>Iodine is a crucial nutrient that plays a vital role in the proper functioning of the thyroid gland, which is responsible for regulating metabolism, growth, and development. By supplementing with sodium iodide, individuals can potentially support thyroid health and address any deficiencies in this essential mineral.</p>', 'Sodium iodide', 24),
	(97, '<p>Potassium iodide is a form of the essential mineral iodine that is often used in dietary supplements. This compound is characterized by its high bioavailability, making it an effective way for individuals to maintain adequate iodine levels within the body.</p>   <p>Iodine is a critical nutrient that plays a vital role in the proper functioning of the thyroid gland, which is responsible for regulating metabolism, growth, and development. By supplementing with potassium iodide, individuals can potentially support thyroid health and address any deficiencies in this essential mineral.</p>', 'Potassium iodide', 24),
	(98, '<p>Sodium fluoride is a form of the mineral fluoride that is often used in dental and medical applications. This compound is known for its ability to strengthen tooth enamel and promote the remineralization of teeth, making it a valuable tool in the prevention of tooth decay.</p>   <p>In addition to its dental benefits, sodium fluoride has also been studied for its potential to support bone health. By enhancing the absorption and utilization of calcium, this compound may help maintain strong and healthy bones, particularly in individuals at risk of osteoporosis.</p>', 'Sodium fluoride', 25),
	(99, '<p>Sodium monofluorophosphate is a form of fluoride that is commonly used in dental products and supplements. This compound is unique in that it provides both fluoride and phosphate, making it a versatile option for promoting strong and healthy teeth.</p>   <p>The fluoride component of sodium monofluorophosphate helps to strengthen tooth enamel and inhibit the growth of harmful bacteria, while the phosphate contributes to the remineralization process. This dual-action approach can be particularly beneficial for individuals at risk of dental caries or other oral health issues.</p>', 'Sodium monofluorophosphate', 25),
	(100, '<p>Molybdenum chloride is a compound that contains the essential trace mineral molybdenum. This mineral plays a crucial role in various metabolic processes within the body, including the breakdown of proteins, fats, and carbohydrates.</p>   <p>Molybdenum chloride is often used in dietary supplements to ensure adequate intake of this important nutrient. It is particularly beneficial for individuals who may be at risk of molybdenum deficiency, such as those with certain genetic disorders or who consume a diet low in this mineral.</p>', 'Molybdenum chloride', 26),
	(101, '<p>Molybdenum glycinate is a form of the essential trace mineral molybdenum that is bound to the amino acid glycine. This combination enhances the bioavailability of molybdenum, making it a more easily absorbed and utilized form of the nutrient.</p>   <p>Molybdenum plays a crucial role in various metabolic processes, including the breakdown of proteins, fats, and carbohydrates. It also supports the conversion of sulfite to sulfate, which helps to eliminate harmful substances from the body.</p>', 'Molybdenum glycinate', 26);

-- Dumping structure for table supplements.food
CREATE TABLE IF NOT EXISTS `food` (
  `food_id` int NOT NULL AUTO_INCREMENT,
  `food_description` text,
  `food_name` varchar(255) NOT NULL,
  `food_image` varchar(255) DEFAULT NULL,
  `nutritive_value` text,
  PRIMARY KEY (`food_id`),
  UNIQUE KEY `UKowcaxj73hkgavmpqaivj5o4yb` (`food_name`)
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.food: ~16 rows (approximately)
INSERT INTO `food` (`food_id`, `food_description`, `food_name`, `food_image`, `nutritive_value`) VALUES
	(1, 'Beef is a nutrient-dense meat that has long been a staple in many diets around the world. Known for its high protein content, beef also provides a range of essential vitamins and minerals, including iron, zinc, and B vitamins.', 'Beef', '/images/food/1725025830430.webp', NULL),
	(16, 'Chicken is a popular and versatile protein source that offers a range of health benefits. As a lean meat, chicken is low in fat and high in protein, making it an excellent choice for those looking to maintain a healthy diet.', 'Chicken', '/images/food/1725025056650.webp', NULL),
	(17, 'Pork is a popular and versatile meat that offers a range of nutritional benefits. As a source of high-quality protein, pork provides essential amino acids that support muscle growth and maintenance.', 'Pork', '/images/food/1725025275403.webp', NULL),
	(18, 'Eggs are a nutrient-dense food that have long been recognized for their exceptional nutritional profile. Packed with high-quality protein, eggs also contain a variety of essential vitamins and minerals, including vitamin A, vitamin D, and choline.', 'Eggs', '/images/food/1725025419668.webp', NULL),
	(19, 'Butter is a dairy product that has long been a staple in many kitchens around the world. While it has been the subject of much debate regarding its health effects, recent research has suggested that butter can be enjoyed as part of a balanced diet.', 'Butter', '/images/food/1725025434340.webp', NULL),
	(20, 'Milk is a nutrient-dense beverage that has long been recognized as an essential component of a healthy and balanced diet. As a source of high-quality protein, milk also contains a variety of essential vitamins and minerals, including calcium, vitamin D, and riboflavin.', 'Milk', '/images/food/1725025449142.webp', NULL),
	(21, 'Strawberries are a beloved fruit known for their vibrant red color, sweet flavor, and impressive nutritional profile. As a rich source of vitamin C, these juicy berries can help support immune function and skin health.', 'Strawberries', '/images/food/1725025497808.webp', NULL),
	(22, 'Pomegranates are a unique and flavorful fruit known for their vibrant red color and abundance of juicy, edible seeds. Beyond their appealing aesthetic, pomegranates are also packed with a wide range of beneficial nutrients and compounds.', 'Pomegranate', '/images/food/1725025516133.webp', NULL),
	(23, 'Avocado is a nutrient-dense fruit rich in monounsaturated fats, fiber, vitamins, and antioxidants, making it a heart-healthy addition to the diet.', 'Avocado', '/images/food/1725025613426.webp', NULL),
	(24, 'Bananas are a potassium-rich fruit that provide natural carbohydrates and fiber, supporting energy levels and digestive health.', 'Banana', '/images/food/1725025636238.webp', NULL),
	(25, 'Carrots are a vibrant, crunchy vegetable high in beta-carotene, a powerful antioxidant that promotes eye health and immune function.', 'Carrots', '/images/food/1725025655100.webp', NULL),
	(26, 'Garlic is a flavorful bulb that contains allicin, a compound with potent antimicrobial and anti-inflammatory properties, making it a beneficial addition to a healthy diet.', 'Garlic', '/images/food/1725025677575.webp', NULL),
	(27, 'Oranges are a citrus fruit rich in vitamin C, an essential nutrient that supports immune function and collagen production for healthy skin.', 'Orange', '/images/food/1725025692782.webp', NULL),
	(28, 'Spinach is a leafy green packed with folate, iron, and antioxidants, contributing to red blood cell production and overall cellular health.', 'Spinach', '/images/food/1725025710109.webp', NULL),
	(29, 'Tomatoes are a nutrient-dense fruit high in lycopene, a powerful antioxidant that may help reduce the risk of certain types of cancer and heart disease.', 'Tomato', '/images/food/1725025730605.webp', NULL),
	(30, 'Blueberries are a rich source of anthocyanins, antioxidants that may improve brain function, cognitive performance, and overall health.', 'Blueberrie', '/images/food/1725025796008.webp', NULL);

-- Dumping structure for table supplements.food_nutrient_relation
CREATE TABLE IF NOT EXISTS `food_nutrient_relation` (
  `id` int NOT NULL AUTO_INCREMENT,
  `amount` varchar(255) DEFAULT NULL,
  `relation_description` text,
  `food_id` int DEFAULT NULL,
  `form_id` int DEFAULT NULL,
  `nutrient_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK6epm5buhuy70kp3k77l0dfky9` (`food_id`),
  CONSTRAINT `FK6epm5buhuy70kp3k77l0dfky9` FOREIGN KEY (`food_id`) REFERENCES `food` (`food_id`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.food_nutrient_relation: ~61 rows (approximately)
INSERT INTO `food_nutrient_relation` (`id`, `amount`, `relation_description`, `food_id`, `form_id`, `nutrient_id`) VALUES
	(21, '8 mg', '<p>Beef is a surprising source of calcium, a crucial mineral for maintaining strong bones and teeth. Incorporating beef into a balanced diet can help meet your daily calcium needs.</p>', 1, 73, 27),
	(22, '2.2 mg', '<p>Beef is a highly bioavailable source of iron, a vital mineral that supports oxygen transport, energy production, and immune function. Enjoy beef as part of a healthy, balanced diet.</p>', 1, 84, 18),
	(23, '20 mg', '<p>In addition to its iron and calcium content, beef is a good source of magnesium, a mineral that aids in muscle and nerve function, as well as energy metabolism.</p>', 1, 70, 28),
	(24, '200 mg', '<p>Beef is an excellent source of phosphorus, a vital mineral that helps build strong bones and teeth, supports energy production, and plays a role in cell repair and maintenance.</p>', 1, NULL, 13),
	(25, '320mg', '<p>Beef is a significant source of potassium, a vital mineral that helps regulate blood pressure and supports overall heart health. Enjoy beef as part of a balanced diet.</p>', 1, NULL, 14),
	(26, '56 mg', '<p>While beef does contain sodium, it is considered a moderate source. Incorporating beef into a diet with other low-sodium foods can provide a well-rounded nutrient profile.</p>', 1, NULL, 16),
	(27, '4.8 mg', '<p>Beef is rich in zinc, a crucial mineral that supports a healthy immune system, wound healing, and protein synthesis. Enjoy beef as part of a balanced diet.</p>', 1, NULL, 20),
	(28, '0.202 mg', ' <p>Beef is an excellent source of riboflavin (vitamin B2), which supports energy production, red blood cell development, and growth and development. Incorporate beef into a balanced diet.</p>', 1, NULL, 3),
	(29, '4.7 mg', '<p>Beef is a notable source of vitamin B3 (niacin), which is essential for skin, nerve, and digestive system health. Enjoy beef as part of a balanced diet.</p>', 1, NULL, 4),
	(30, '0.36 mg', '<p>Beef is rich in Vitamin B5 (pantothenic acid), which supports energy production, enhances metabolism, and helps synthesize hormones and red blood cells.</p>', 1, NULL, 5),
	(31, '0.4 mg', '<p>Beef is a great source of Vitamin B6, essential for brain health, metabolism, and immune function. It helps in neurotransmitter synthesis and red blood cell formation.</p>', 1, NULL, 6),
	(32, '2.4 mg', '<p>Beef is rich in Vitamin B12, crucial for nerve function, DNA synthesis, and red blood cell production. Adequate intake helps prevent anemia and supports overall energy levels.</p>', 1, NULL, 9),
	(33, '0.1 mg', '<p>Beef contains Vitamin E, an antioxidant that protects cells from damage, supports immune function, and helps maintain healthy skin and eyes, contributing to overall well-being.</p>', 1, NULL, 12),
	(34, '12 mg\r\n', 'Calcium', 16, NULL, 27),
	(35, '0.9 mg', 'Iron', 16, NULL, 18),
	(36, '22 mg', 'Magnesium', 16, NULL, 19),
	(37, '200 mg', 'Phosphorus', 16, NULL, 13),
	(38, '172 mg', 'Potassium', 16, NULL, 14),
	(39, '75 mg', 'Sodium', 16, NULL, 16),
	(40, '0.8 mg', 'Zinc', 16, NULL, 20),
	(41, '0.18 mg', 'Vitamin B2', 16, NULL, 3),
	(42, '8.93 mg', 'Vitamin B3', 16, NULL, 4),
	(43, '1.05 mg', 'Vitamin B5', 16, NULL, 5),
	(44, '0.47 mg', ' Vitamin B6', 16, NULL, 6),
	(45, '0.34 mg', 'Vitamin B12', 16, NULL, 9),
	(46, '200 mg', 'Phosphorus', 17, 75, 13),
	(47, '172 mg', 'Phosphorus', 18, 75, 13),
	(48, '24 mg', 'Phosphorus', 19, 75, 13),
	(49, '93 mg', 'Phosphorus', 20, 75, 13),
	(50, '24 mg', 'Phosphorus', 21, 75, 13),
	(51, '36 mg', 'Phosphorus', 22, 75, 13),
	(52, '350 mg', 'Potassium', 17, 77, 14),
	(53, '138 mg', 'Potassium', 18, 77, 14),
	(54, '24 mg', 'Potassium', 19, 77, 14),
	(55, '143mg', 'Potassium', 20, 77, 14),
	(56, '153 mg', 'Potassium', 21, 77, 14),
	(57, '236 mg', 'Potassium', 22, 77, 14),
	(58, '0.324 mg', 'Vitamin A', 19, 47, 1),
	(59, '0.789 mg', 'Vitamin A', 28, 47, 1),
	(60, '0.121 mg', 'Vitamin A', 21, 47, 1),
	(61, '0.137 mg', 'Vitamin A', 29, 47, 1),
	(62, '0.324 mg', 'Vitamin A', 26, 47, 1),
	(63, '0.174 mg', 'Vitamin A', 23, 47, 1),
	(64, '0.844 mg', 'Vitamin A', 25, 47, 1),
	(65, '0.844 mg', 'Vitamin B-1', 25, 49, 2),
	(66, '0.844 mg', 'Vitamin B-1', 23, 49, 2),
	(67, '0.844 mg', 'Vitamin B-1', 24, 49, 2),
	(68, '0.844 mg', 'Vitamin B-1', 19, 49, 2),
	(69, '0.844 mg', 'Vitamin B-1', 20, 49, 2),
	(70, '0.844 mg', 'Vitamin B-1', 17, 49, 2),
	(71, '0.844 mg', 'Vitamin B-1', 27, 49, 2),
	(72, '0.844 mg', 'Vitamin B-1', 28, 49, 2),
	(73, '0.844 mg', 'Vitamin B-1', 29, 49, 2),
	(74, '0.844 mg', 'Vitamin B-2', 29, 51, 3),
	(75, '0.844 mg', 'Vitamin B-2', 24, 51, 3),
	(76, '0.844 mg', 'Vitamin B-2', 27, 51, 3),
	(77, '0.844 mg', 'Vitamin B-2', 22, 51, 3),
	(78, '0.844 mg', 'Vitamin B-2', 17, 51, 3),
	(79, '0.844 mg', 'Vitamin B-2', 28, 51, 3),
	(80, '0.844 mg', 'Vitamin B-2', 30, 51, 3),
	(81, '0.844 mg', 'Vitamin B-2', 26, 51, 3);

-- Dumping structure for table supplements.mineral
CREATE TABLE IF NOT EXISTS `mineral` (
  `id` int NOT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `dosage` text,
  `short_description` text,
  `nutrient_type` varchar(255) DEFAULT NULL,
  `image_link` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKawq86r6o1qytbolxrr9no4412` (`name`),
  UNIQUE KEY `UKcc0pw5cy63l3y9f7ola5r0coo` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.mineral: ~16 rows (approximately)
INSERT INTO `mineral` (`id`, `full_name`, `name`, `dosage`, `short_description`, `nutrient_type`, `image_link`) VALUES
	(13, 'P', 'Phosphorus', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>100 mg</td>     <td>100 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months*</td>     <td>275 mg</td>     <td>275 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>460 mg</td>     <td>460 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>500 mg</td>     <td>500 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>1,250 mg</td>     <td>1,250 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>1,250 mg</td>     <td>1,250 mg</td>     <td>1,250 mg</td>     <td>1,250 mg</td>   </tr>   <tr>     <td>19+ years</td>     <td>700 mg</td>     <td>700 mg</td>     <td>700 mg</td>     <td>700 mg</td>   </tr> </table>', 'Phosphorus is a remarkable mineral that plays a crucial role in various aspects of human health. As an essential nutrient, it is involved in numerous physiological processes, contributing to the maintenance of strong bones and teeth, the regulation of energy metabolism, and the support of cell structure and function.', 'minerals', '/images/minerals/1725024310720.webp'),
	(14, 'K', 'Potassium', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>400 mg</td>     <td>400 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>860 mg</td>     <td>860 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>2,000 mg</td>     <td>2,000 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>2,300 mg</td>     <td>2,300 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>2,500 mg</td>     <td>2,300 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>3,000 mg</td>     <td>2,300 mg</td>     <td>2,600 mg</td>     <td>2,500 mg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>3,400 mg</td>     <td>2,600 mg</td>     <td>2,900 mg</td>     <td>2,800 mg</td>   </tr>   <tr>     <td>51+ years</td>     <td>3,400 mg</td>     <td>2,600 mg</td>     <td></td>     <td></td>   </tr> </table>', 'Potassium is an essential mineral that plays a crucial role in the proper functioning of the human body. As an electrolyte, it is responsible for maintaining a healthy balance of fluids and electrical signals throughout the body, contributing to the regulation of various physiological processes.', 'minerals', '/images/minerals/1725024342371.webp'),
	(15, 'S', 'Sulfur', '13 mg/kg per 24h', 'Sulfur is a remarkable mineral that plays a crucial role in various aspects of human health. While it may not be as well-known as some of its counterparts, sulfur is an essential nutrient that contributes to the proper functioning of the body, supporting the maintenance of healthy skin, hair, and nails, as well as the detoxification processes.', 'minerals', '/images/minerals/1725024368504.webp'),
	(16, 'Na', 'Sodium', 'Less than 2,300 mg per day', 'Sodium is an essential mineral that plays a crucial role in the proper functioning of the human body. As a vital electrolyte, it is responsible for maintaining a healthy balance of fluids and electrical signals throughout the body, contributing to the regulation of various physiological processes.', 'minerals', '/images/minerals/1725024391285.webp'),
	(17, 'Cl', 'Chloride', 'Less than 2,300 mg per day', 'Chloride is an essential mineral that often goes unnoticed, but it plays a crucial role in the proper functioning of the human body. As an electrolyte, it works in tandem with other minerals like sodium and potassium to maintain a healthy balance of fluids and electrical signals throughout the body.', 'minerals', '/images/minerals/1725024419748.webp'),
	(18, 'Fe', 'Iron', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>0.27 mg*</td>     <td>0.27 mg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>11 mg</td>     <td>11 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>7 mg</td>     <td>7 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>10 mg</td>     <td>10 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>8 mg</td>     <td>8 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>11 mg</td>     <td>15 mg</td>     <td>27 mg</td>     <td>10 mg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>8 mg</td>     <td>18 mg</td>     <td>27 mg</td>     <td>9 mg</td>   </tr>   <tr>     <td>51+ years</td>     <td>8 mg</td>     <td>8 mg</td>     <td></td>     <td></td>   </tr> </table>', 'nullaIron is an essential mineral that plays a crucial role in the proper functioning of the human body. It is a key component of hemoglobin, the protein in red blood cells responsible for transporting oxygen throughout the body, making it vital for maintaining healthy blood and supporting overall energy levels.', 'minerals', '/images/minerals/1725024441110.webp'),
	(19, 'Se', 'Selenium', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>15 mcg*</td>     <td>15 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>20 mcg*</td>     <td>20 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>20 mcg</td>     <td>20 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>30 mcg</td>     <td>30 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>40 mcg</td>     <td>40 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>55 mcg</td>     <td>55 mcg</td>     <td>60 mcg</td>     <td>70 mcg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>55 mcg</td>     <td>55 mcg</td>     <td>60 mcg</td>     <td>70 mcg</td>   </tr>   <tr>     <td>51+ years</td>     <td>55 mcg</td>     <td>55 mcg</td>     <td></td>     <td></td>   </tr> </table>', 'Selenium is a trace mineral that plays a crucial role in the proper functioning of the human body. While it may not be as well-known as some of its counterparts, selenium is an essential nutrient that contributes to the maintenance of a healthy immune system and the prevention of various chronic diseases.', 'minerals', '/images/minerals/1725024477397.webp'),
	(20, 'Zn', 'Zinc', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>2 mg</td>     <td>2 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>3 mg</td>     <td>3 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>3 mg</td>     <td>3 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>5 mg</td>     <td>5 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>8 mg</td>     <td>8 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>11 mg</td>     <td>9 mg</td>     <td>12 mg</td>     <td>13 mg</td>   </tr>   <tr>     <td>19+ years</td>     <td>11 mg</td>     <td>8 mg</td>     <td>11 mg</td>     <td>12 mg</td>   </tr> </table>', 'Zinc is an essential mineral that plays a crucial role in a wide range of physiological processes within the human body. While it may not be as well-known as some of its counterparts, zinc is a versatile nutrient that contributes to the maintenance of a healthy immune system, the repair of cells, and the proper function of the senses.', 'minerals', '/images/minerals/1725024496357.webp'),
	(21, 'Mn', 'Manganese', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>0.003 mg</td>     <td>0.003 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>0.6 mg</td>     <td>0.6 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>1.2 mg</td>     <td>1.2 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>1.5 mg</td>     <td>1.5 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>1.9 mg</td>     <td>1.6 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>2.2 mg</td>     <td>1.6 mg</td>     <td>2.0 mg</td>     <td>2.6 mg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>2.3 mg</td>     <td>1.8 mg</td>     <td>2.0 mg</td>     <td>2.6 mg</td>   </tr>   <tr>     <td>51+ years</td>     <td>2.3 mg</td>     <td>1.8 mg</td>     <td></td>     <td></td>   </tr> </table>', 'Manganese is an essential trace mineral that often goes unnoticed, but it plays a crucial role in the proper functioning of the human body. As a cofactor for numerous enzymes, manganese serves as a catalyst for various metabolic processes, ensuring the body\'s systems operate efficiently and effectively.', 'minerals', '/images/minerals/1725024535805.webp'),
	(22, 'Cr', 'Chromium', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>0.2 mcg</td>     <td>0.2 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months*</td>     <td>5.5 mcg</td>     <td>5.5 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>11 mcg</td>     <td>11 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>15 mcg</td>     <td>15 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>25 mcg</td>     <td>21 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>35 mcg</td>     <td>24 mcg</td>     <td>29 mcg</td>     <td>44 mcg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>35 mcg</td>     <td>25 mcg</td>     <td>30 mcg</td>     <td>45 mcg</td>   </tr>   <tr>     <td>51+ years</td>     <td>30 mcg</td>     <td>20 mcg</td>     <td></td>     <td></td>   </tr> </table>', 'Chromium is an essential trace mineral that plays a vital role in the regulation of blood sugar levels. While it may not be as well-known as some of its counterparts, chromium is a crucial nutrient that contributes to the proper functioning of the body\'s insulin and glucose metabolism.', 'minerals', '/images/minerals/1725024560209.webp'),
	(23, 'Cu', 'Copper', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>200 mcg</td>     <td>200 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months*</td>     <td>220 mcg</td>     <td>220 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>340 mcg</td>     <td>340 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>440 mcg</td>     <td>440 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>700 mcg</td>     <td>700 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>890 mcg</td>     <td>890 mcg</td>     <td>1,000 mcg</td>     <td>1,300 mcg</td>   </tr>   <tr>     <td>19+ years</td>     <td>900 mcg</td>     <td>900 mcg</td>     <td>1,000 mcg</td>     <td>1,300 mcg</td>   </tr> </table>', 'Copper is an essential trace mineral that plays a vital role in the proper functioning of the human body. While it may not be as well-known as some of its counterparts, copper is a versatile nutrient that contributes to a wide range of physiological processes, from the formation of red blood cells to the maintenance of healthy skin and hair.', 'minerals', '/images/minerals/1725024595268.webp'),
	(24, 'I', 'Iodine', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>110 mcg*</td>     <td>110 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>130 mcg*</td>     <td>130 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>90 mcg</td>     <td>90 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>90 mcg</td>     <td>90 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>120 mcg</td>     <td>120 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>150 mcg</td>     <td>150 mcg</td>     <td>220 mcg</td>     <td>290 mcg</td>   </tr>   <tr>     <td>19+ years</td>     <td>150 mcg</td>     <td>150 mcg</td>     <td>220 mcg</td>     <td>290 mcg</td>   </tr> </table>', 'Iodine is an essential trace mineral that plays a crucial role in the proper functioning of the thyroid gland, a small but mighty endocrine organ located in the neck. While it may not be as well-known as some of its counterparts, iodine is a vital nutrient that contributes to the regulation of metabolism, energy production, and overall bodily function.', 'minerals', '/images/minerals/1725024618384.webp'),
	(25, 'F', 'Fluoride', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>0.01 mg</td>     <td>0.01 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>0.5 mg</td>     <td>0.5 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>0.7 mg</td>     <td>0.7 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>1 mg</td>     <td>1 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>2 mg</td>     <td>2 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>3 mg</td>     <td>3 mg</td>     <td>3 mg</td>     <td>3 mg</td>   </tr>   <tr>     <td>19+ years</td>     <td>4 mg</td>     <td>3 mg</td>     <td>3 mg</td>     <td>3 mg</td>   </tr> </table>', 'Fluoride is a mineral that has long been recognized for its crucial role in maintaining the health of our teeth and gums. While it may not be as widely known for its broader health benefits, fluoride is a versatile compound that contributes to the overall well-being of the human body.', 'minerals', '/images/minerals/1725024717835.webp'),
	(26, 'Mo', 'Molybdenum', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months</td>     <td>2 mcg*</td>     <td>2 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months</td>     <td>3 mcg*</td>     <td>3 mcg*</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>17 mcg</td>     <td>17 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>22 mcg</td>     <td>22 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>34 mcg</td>     <td>34 mcg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>43 mcg</td>     <td>43 mcg</td>     <td>50 mcg</td>     <td>50 mcg</td>   </tr>   <tr>     <td>19+ years</td>     <td>45 mcg</td>     <td>45 mcg</td>     <td>50 mcg</td>     <td>50 mcg</td>   </tr> </table>', 'Molybdenum is a trace mineral that, despite its relatively low profile, plays a crucial role in the proper functioning of the human body. While it may not be as well-known as some of its more prominent counterparts, molybdenum is a versatile nutrient that contributes to a wide range of physiological processes, from the metabolism of proteins to the detoxification of harmful compounds.', 'minerals', '/images/minerals/1725024741140.webp'),
	(27, 'Ca', 'Calcium', '<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnant</th>     <th>Lactating</th>   </tr>   <tr>     <td>0–6 months*</td>     <td>200 mg</td>     <td>200 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months*</td>     <td>260 mg</td>     <td>260 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>700 mg</td>     <td>700 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>1,000 mg</td>     <td>1,000 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>1,300 mg</td>     <td>1,300 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>1,300 mg</td>     <td>1,300 mg</td>     <td>1,300 mg</td>     <td>1,300 mg</td>   </tr>   <tr>     <td>19–50 years</td>     <td>1,000 mg</td>     <td>1,000 mg</td>     <td>1,000 mg</td>     <td>1,000 mg</td>   </tr>   <tr>     <td>51–70 years</td>     <td>1,000 mg</td>     <td>1,200 mg</td>     <td></td>     <td></td>   </tr>   <tr>     <td>>70+ years</td>     <td>1,200 mg</td>     <td>1,200 mg</td>     <td></td>     <td></td>   </tr> </table>', 'Calcium is a remarkable mineral that plays a crucial role in various aspects of human health. As an essential nutrient, it is primarily known for its importance in the development and maintenance of strong, healthy bones and teeth. However, its functions extend far beyond just bone health.', 'minerals', '/images/minerals/1725024276246.webp'),
	(28, 'Mg', 'Magnesium', '   <h2>Recommended Daily Allowance (RDA) for Magnesium by Age and Sex</h2>\n    <p>The following table shows the recommended daily allowance (RDA) for magnesium intake by age and sex, according to the ODSTrusted Source.</p>\n    <table>\n        <thead>\n            <tr>\n                <th>Age</th>\n                <th>Male</th>\n                <th>Female</th>\n            </tr>\n        </thead>\n        <tbody>\n            <tr>\n                <td>1–3 years</td>\n                <td>80 mg</td>\n                <td>80 mg</td>\n            </tr>\n            <tr>\n                <td>4–8 years</td>\n                <td>130 mg</td>\n                <td>130 mg</td>\n            </tr>\n            <tr>\n                <td>9–13 years</td>\n                <td>240 mg</td>\n                <td>240 mg</td>\n            </tr>\n            <tr>\n                <td>14–18 years</td>\n                <td>410 mg</td>\n                <td>360 mg</td>\n            </tr>\n            <tr>\n                <td>19–30 years</td>\n                <td>400 mg</td>\n                <td>310 mg</td>\n            </tr>\n            <tr>\n                <td>31–50 years</td>\n                <td>420 mg</td>\n                <td>320 mg</td>\n            </tr>\n            <tr>\n                <td>51+ years</td>\n                <td>420 mg</td>\n                <td>320 mg</td>\n            </tr>\n        </tbody>\n    </table>\n    <p>People should increase their magnesium intake by around 40 mg per day during pregnancy.</p>\n    <p>Experts base the adequate intake for babies under 1 year old on the amounts found in breastmilk.</p>', 'Magnesium plays a role in over 300 enzyme reactions in the human body. Magnesium functions include helping with muscle and nerve function, regulating blood pressure, and supporting the immune system.', 'minerals', '/images/minerals/magnesium.webp');

-- Dumping structure for table supplements.nutrient_interactions
CREATE TABLE IF NOT EXISTS `nutrient_interactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nutrient1` int NOT NULL,
  `interaction_description` varchar(255) DEFAULT NULL,
  `nutrient2` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.nutrient_interactions: ~4 rows (approximately)
INSERT INTO `nutrient_interactions` (`id`, `nutrient1`, `interaction_description`, `nutrient2`) VALUES
	(1, 4, 'Iron Interacts with magnesium way too much!', 1),
	(2, 604, 'Selenium work better with Iron', 4),
	(3, 619, 'Vitamin C helps Iron to absorb', 4),
	(4, 619, 'Magnesium works well with Vitamin C', 1);

-- Dumping structure for table supplements.nutrient_seq
CREATE TABLE IF NOT EXISTS `nutrient_seq` (
  `next_val` bigint DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.nutrient_seq: ~1 rows (approximately)
INSERT INTO `nutrient_seq` (`next_val`) VALUES
	(30);

-- Dumping structure for table supplements.user
CREATE TABLE IF NOT EXISTS `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `password` varchar(255) NOT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKsb8bbouer5wak8vyiiy4pf2bx` (`username`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.user: ~2 rows (approximately)
INSERT INTO `user` (`id`, `password`, `username`) VALUES
	(1, '$2a$10$MWLL0W0Q72h3MeveWkTJQuATuRgGlOoU49aOTb4sT7q9uBuJ8GYKq', 'admin'),
	(18, '$2a$10$sUpWW1945I6w/1NK4DrbTefEcXm5LLTtfVdoTulOz684UEydsdCEi', 'newusername');

-- Dumping structure for table supplements.vitamin
CREATE TABLE IF NOT EXISTS `vitamin` (
  `id` int NOT NULL,
  `full_name` varchar(255) DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `dosage` text,
  `short_description` text,
  `nutrient_type` varchar(255) DEFAULT NULL,
  `image_link` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UKawq86r6o1qytbolxrr9no4412` (`name`),
  UNIQUE KEY `UKcc0pw5cy63l3y9f7ola5r0coo` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Dumping data for table supplements.vitamin: ~12 rows (approximately)
INSERT INTO `vitamin` (`id`, `full_name`, `name`, `dosage`, `short_description`, `nutrient_type`, `image_link`) VALUES
	(1, 'Retinol', 'Vitamin A', '"<table>   <tr>     <th>Age</th>     <th>Male</th>     <th>Female</th>     <th>Pregnancy</th>     <th>Lactation</th>   </tr>   <tr>     <td>Birth to 6 months*</td>     <td>400 mcg RAE</td>     <td>400 mcg RAE</td>     <td></td>     <td></td>   </tr>   <tr>     <td>7–12 months*</td>     <td>500 mcg RAE</td>     <td>500 mcg RAE</td>     <td></td>     <td></td>   </tr>   <tr>     <td>1–3 years</td>     <td>300 mcg RAE</td>     <td>300 mcg RAE</td>     <td></td>     <td></td>   </tr>   <tr>     <td>4–8 years</td>     <td>400 mcg RAE</td>     <td>400 mcg RAE</td>     <td></td>     <td></td>   </tr>   <tr>     <td>9–13 years</td>     <td>600 mcg RAE</td>     <td>600 mcg RAE</td>     <td></td>     <td></td>   </tr>   <tr>     <td>14–18 years</td>     <td>900 mcg RAE</td>     <td>700 mcg RAE</td>     <td>750 mcg RAE</td>     <td>1,200 mcg RAE</td>   </tr>   <tr>     <td>19–50 years</td>     <td>900 mcg RAE</td>     <td>700 mcg RAE</td>     <td>770 mcg RAE</td>     <td>1,300 mcg RAE</td>   </tr>   <tr>     <td>51+ years</td>     <td>900 mcg RAE</td>     <td>700 mcg RAE</td>     <td></td>     <td></td>   </tr> </table>"', 'Vitamin A is a vital nutrient that plays a key role in many processes in our body. Also known as retinol, this vitamin is necessary for the normal functioning of vision, the immune system, skin, and many other systems.', 'vitamins', '/images/vitamins/1725002255392.webp'),
	(2, 'Thiamin', 'Vitamin B-1', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months*</td>       <td>0.2 mg</td>       <td>0.2 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months*</td>       <td>0.3 mg</td>       <td>0.3 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>0.5 mg</td>       <td>0.5 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>0.6 mg</td>       <td>0.6 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>0.9 mg</td>       <td>0.9 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>1.2 mg</td>       <td>1.0 mg</td>       <td>1.4 mg</td>       <td>1.4 mg</td>     </tr>     <tr>       <td>19–50 years</td>       <td>1.2 mg</td>       <td>1.1 mg</td>       <td>1.4 mg</td>       <td>1.4 mg</td>     </tr>     <tr>       <td>51+ years</td>       <td>1.2 mg</td>       <td>1.1 mg</td>       <td></td>       <td></td>     </tr>   </tbody> </table>', 'Vitamin B-1, also known as thiamine, is an essential nutrient that plays a crucial role in the body\'s metabolism and overall health. This water-soluble vitamin is vital for converting food into energy, supporting nerve function, and maintaining a healthy cardiovascular system.', 'vitamins', '/images/vitamins/1725021642970.webp'),
	(3, 'Riboflavin', 'Vitamin B-2', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months*</td>       <td>0.3 mg</td>       <td>0.3 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months*</td>       <td>0.4 mg</td>       <td>0.4 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>0.5 mg</td>       <td>0.5 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>0.6 mg</td>       <td>0.6 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>0.9 mg</td>       <td>0.9 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>1.3 mg</td>       <td>1.0 mg</td>       <td>1.4 mg</td>       <td>1.6 mg</td>     </tr>     <tr>       <td>19–50 years</td>       <td>1.3 mg</td>       <td>1.1 mg</td>       <td>1.4 mg</td>       <td>1.6 mg</td>     </tr>     <tr>       <td>51+ years</td>       <td>1.3 mg</td>       <td>1.1 mg</td>       <td></td>       <td></td>     </tr>   </tbody> </table>', 'Vitamin B-2, also known as riboflavin, is a vital nutrient that plays a crucial role in various bodily functions. This water-soluble vitamin is essential for converting food into energy, maintaining healthy skin and vision, and supporting overall cellular growth and development.', 'vitamins', '/images/vitamins/1725023265959.webp'),
	(4, 'Niacin', 'Vitamin B-3', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months*</td>       <td>2 mg</td>       <td>2 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months*</td>       <td>4 mg NE</td>       <td>4 mg NE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>6 mg NE</td>       <td>6 mg NE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>8 mg NE</td>       <td>8 mg NE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>12 mg NE</td>       <td>12 mg NE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>16 mg NE</td>       <td>14 mg NE</td>       <td>18 mg NE</td>       <td>17 mg NE</td>     </tr>     <tr>       <td>19+ years</td>       <td>16 mg NE</td>       <td>14 mg NE</td>       <td>18 mg NE</td>       <td>17 mg NE</td>     </tr>   </tbody> </table>', 'Vitamin B-3, also known as niacin, is a remarkable nutrient that plays a multifaceted role in human health. As a water-soluble vitamin, it is essential for various physiological processes, including energy metabolism, DNA repair, and maintaining a healthy cardiovascular system.', 'vitamins', '/images/vitamins/1725023301785.webp'),
	(5, 'Pantothenic Acid', 'Vitamin B-5', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months</td>       <td>1.7 mg</td>       <td>1.7 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months</td>       <td>1.8 mg</td>       <td>1.8 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>2 mg</td>       <td>2 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>3 mg</td>       <td>3 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>4 mg</td>       <td>4 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>5 mg</td>       <td>5 mg</td>       <td>6 mg</td>       <td>7 mg</td>     </tr>     <tr>       <td>19+ years</td>       <td>5 mg</td>       <td>5 mg</td>       <td>6 mg</td>       <td>7 mg</td>     </tr>   </tbody> </table>', 'Vitamin B-5, also known as pantothenic acid, is a remarkable nutrient that plays a crucial role in various aspects of human health. As a water-soluble vitamin, it is essential for the proper functioning of the body, contributing to energy production, hormone synthesis, and the maintenance of healthy skin and hair.', 'vitamins', '/images/vitamins/1725023342940.webp'),
	(6, 'Pyridoxine', 'Vitamin B-6', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months</td>       <td>0.1 mg*</td>       <td>0.1 mg*</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months</td>       <td>0.3 mg*</td>       <td>0.3 mg*</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>0.5 mg</td>       <td>0.5 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>0.6 mg</td>       <td>0.6 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>1.0 mg</td>       <td>1.0 mg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>1.3 mg</td>       <td>1.2 mg</td>       <td>1.9 mg</td>       <td>2.0 mg</td>     </tr>     <tr>       <td>19–50 years</td>       <td>1.3 mg</td>       <td>1.3 mg</td>       <td>1.9 mg</td>       <td>2.0 mg</td>     </tr>     <tr>       <td>51+ years</td>       <td>1.7 mg</td>       <td>1.5 mg</td>       <td></td>       <td></td>     </tr>   </tbody> </table>', 'Vitamin B-6, also known as pyridoxine, is a remarkable nutrient that plays a crucial role in various aspects of human health. As a water-soluble vitamin, it is essential for the proper functioning of the body, contributing to enzyme activity, red blood cell formation, and the maintenance of a healthy nervous system.', 'vitamins', '/images/vitamins/1725023378190.webp'),
	(7, 'Biotin', 'Vitamin B-7', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months</td>       <td>5 mcg</td>       <td>5 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months</td>       <td>6 mcg</td>       <td>6 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>8 mcg</td>       <td>8 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>12 mcg</td>       <td>12 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>20 mcg</td>       <td>20 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>25 mcg</td>       <td>25 mcg</td>       <td>30 mcg</td>       <td>35 mcg</td>     </tr>     <tr>       <td>19+ years</td>       <td>30 mcg</td>       <td>30 mcg</td>       <td>30 mcg</td>       <td>35 mcg</td>     </tr>   </tbody> </table>', 'nullaVitamin B-7, also known as biotin, is a remarkable nutrient that plays a crucial role in various aspects of human health. As a water-soluble vitamin, it is essential for the proper functioning of the body, contributing to the metabolism of fats, proteins, and carbohydrates, as well as the maintenance of healthy skin, hair, and nails.', 'vitamins', '/images/vitamins/1725023417843.webp'),
	(8, 'Folate', 'Vitamin B-9', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months*</td>       <td>65 mcg DFE*</td>       <td>65 mcg DFE*</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months*</td>       <td>80 mcg DFE*</td>       <td>80 mcg DFE*</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>150 mcg DFE</td>       <td>150 mcg DFE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>200 mcg DFE</td>       <td>200 mcg DFE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>300 mcg DFE</td>       <td>300 mcg DFE</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>400 mcg DFE</td>       <td>400 mcg DFE</td>       <td>600 mcg DFE</td>       <td>500 mcg DFE</td>     </tr>     <tr>       <td>19+ years</td>       <td>400 mcg DFE</td>       <td>400 mcg DFE</td>       <td>600 mcg DFE</td>       <td>500 mcg DFE</td>     </tr>   </tbody> </table>', 'Vitamin B-9, also known as folate, is a remarkable nutrient that plays a crucial role in various aspects of human health. As a water-soluble vitamin, it is essential for the proper functioning of the body, contributing to cell division, DNA synthesis, and the maintenance of a healthy nervous system.', 'vitamins', '/images/vitamins/1725023440222.webp'),
	(9, 'Cyanocobalamin', 'Vitamin B-12', '<table>   <thead>     <tr>       <th>Age</th>       <th>Male</th>       <th>Female</th>       <th>Pregnancy</th>       <th>Lactation</th>     </tr>   </thead>   <tbody>     <tr>       <td>Birth to 6 months*</td>       <td>0.4 mcg</td>       <td>0.4 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>7–12 months*</td>       <td>0.5 mcg</td>       <td>0.5 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>1–3 years</td>       <td>0.9 mcg</td>       <td>0.9 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>4–8 years</td>       <td>1.2 mcg</td>       <td>1.2 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>9–13 years</td>       <td>1.8 mcg</td>       <td>1.8 mcg</td>       <td></td>       <td></td>     </tr>     <tr>       <td>14–18 years</td>       <td>2.4 mcg</td>       <td>2.4 mcg</td>       <td>2.6 mcg</td>       <td>2.8 mcg</td>     </tr>     <tr>       <td>19+ years</td>       <td>2.4 mcg</td>       <td>2.4 mcg</td>       <td>2.6 mcg</td>       <td>2.8 mcg</td>     </tr>   </tbody> </table>', 'Vitamin B-12, also known as Cyanocobalamin, is a remarkable nutrient that plays a crucial role in various aspects of human health. As a water-soluble vitamin, it is essential for the proper functioning of the body, contributing to the formation of red blood cells, the maintenance of a healthy nervous system, and the support of energy production.', 'vitamins', '/images/vitamins/1725023479259.webp'),
	(10, 'Ascorbic Acid', 'Vitamin C', ' <p>The Recommended Dietary Allowance (RDA) for Vitamin C is the average daily level of intake sufficient to meet the nutrient requirements of 97-98% of healthy individuals in a particular life stage and gender group. The current RDA for Vitamin C is:</p>    <ul>        <li><strong>Adults:</strong> 75-90 mg per day</li>        <li><strong>Pregnant women:</strong> 85 mg per day</li>        <li><strong>Breastfeeding women:</strong> 120 mg per day</li>        <li><strong>Infants and children:</strong> 15-75 mg per day (depending on age)</li>    </ul>', 'Vitamin C is a water-soluble essential vitamin that can be found in fruits and vegetables, especially citrus. Humans are unable to synthesize vitamin C from their bodies, so it must be acquired through dietary intake. Vitamin C is important for immune system function and is a powerful antioxidant. It also acts as a cofactor for collagen synthesis.', 'vitamins', '/images/vitamins/vitamin_c.webp'),
	(11, 'Calciferol', 'Vitamin D', '<table>\r\n  <tr>\r\n    <th>Age</th>\r\n    <th>Male</th>\r\n    <th>Female</th>\r\n    <th>Pregnancy</th>\r\n    <th>Lactation</th>\r\n  </tr>\r\n  <tr>\r\n    <td>0-12 months*</td>\r\n    <td>10 mcg (400 IU)</td>\r\n    <td>10 mcg (400 IU)</td>\r\n    <td></td>\r\n    <td></td>\r\n  </tr>\r\n  <tr>\r\n    <td>1–13 years</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td></td>\r\n    <td></td>\r\n  </tr>\r\n  <tr>\r\n    <td>14–18 years</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n  </tr>\r\n  <tr>\r\n    <td>19–50 years</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n  </tr>\r\n  <tr>\r\n    <td>51–70 years</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td>15 mcg (600 IU)</td>\r\n    <td></td>\r\n    <td></td>\r\n  </tr>\r\n  <tr>\r\n    <td>&gt;70 years</td>\r\n    <td>20 mcg (800 IU)</td>\r\n    <td>20 mcg (800 IU)</td>\r\n    <td></td>\r\n    <td></td>\r\n  </tr>\r\n</table>a', 'Vitamin D, often referred to as the "sunshine vitamin," is a fat-soluble nutrient essential for numerous bodily functions. Unlike most vitamins, vitamin D is predominantly obtained through the skin\'s exposure to ultraviolet B (UVB) rays from the sun, rather than dietary sources.', 'vitamins', '/images/vitamins/VITAMIN D.webp'),
	(12, 'Tocopherol', 'Vitamin E', '<table>\r\n  <thead>\r\n    <tr>\r\n      <th>Age</th>\r\n      <th>Males</th>\r\n      <th>Females</th>\r\n      <th>Pregnancy</th>\r\n      <th>Lactation</th>\r\n    </tr>\r\n  </thead>\r\n  <tbody>\r\n    <tr>\r\n      <td>0–6 months*</td>\r\n      <td>4 mg</td>\r\n      <td>4 mg</td>\r\n      <td></td>\r\n      <td></td>\r\n    </tr>\r\n    <tr>\r\n      <td>7–12 months*</td>\r\n      <td>5 mg</td>\r\n      <td>5 mg</td>\r\n      <td></td>\r\n      <td></td>\r\n    </tr>\r\n    <tr>\r\n      <td>1–3 years</td>\r\n      <td>6 mg</td>\r\n      <td>6 mg</td>\r\n      <td></td>\r\n      <td></td>\r\n    </tr>\r\n    <tr>\r\n      <td>4–8 years</td>\r\n      <td>7 mg</td>\r\n      <td>7 mg</td>\r\n      <td></td>\r\n      <td></td>\r\n    </tr>\r\n    <tr>\r\n      <td>9–13 years</td>\r\n      <td>11 mg</td>\r\n      <td>11 mg</td>\r\n      <td></td>\r\n      <td></td>\r\n    </tr>\r\n    <tr>\r\n      <td>14+ years</td>\r\n      <td>15 mg</td>\r\n      <td>15 mg</td>\r\n      <td>15 mg</td>\r\n      <td>19 mg</td>\r\n    </tr>\r\n  </tbody>\r\n</table>', 'Vitamin E is a fat-soluble nutrient that plays a crucial role in supporting overall health and well-being. This essential vitamin is composed of a group of eight distinct compounds, each with their own unique properties and health benefits.', 'vitamins', '/images/vitamins/1725023946975.webp');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
